name: Scala Publish

on:
  workflow_dispatch

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN_WITH_READ_PACKAGES_SCOPE }}
  
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Setup sbt launcher
      uses: sbt/setup-sbt@v1
    - name: Test/Publish
      run: sbt test publish
